### ISSUE TITLE
How to style more/less text?

### ISSUE THREAD

**Issue by MirzaOglecevac** [BrightspaceUI/more-less#19]
Is there any way to style toggle text(more/less)? I know how to change this text but i cant figure it out how to style it by css?

**Comment by omsmith** [comment]
Hi @MirzaOglecevac 

Thanks for the interest and sorry for the late response. We're very happy if you can find a use for or learn from our components; however, their primary purpose is for our internal teams to build our product interfaces and for our partners to extend them. With this in mind, our components don't generally allow for radical re-styling unless necessary in order to maintain a "look & feel".

Feel free to leverage our techniques in your own component. Just make sure to keep [our license](https://github.com/BrightspaceUI/more-less/blob/master/LICENSE) in mind while doing so.

Thanks again!
